src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Entity\Client;
use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Serializer\Groups(['entreprise_id', 'clients', 'commandes', 'employes'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Serializer\Groups(['entreprise_nom', 'clients', 'commandes', 'employes'])]
    private ?string $nom = null;

    #[ORM\Column]
    #[Serializer\Groups(['entreprise_numero_siret', 'clients', 'commandes', 'employes'])]
    private ?int $numero_siret = null;

    #[ORM\Column(length: 255)]
    #[Serializer\Groups(['entreprise_adresse', 'clients', 'commandes', 'employes'])]
    private ?string $adresse = null;

    #[ORM\Column]
    #[Serializer\Groups(['entreprise_code_postal', 'clients', 'commandes', 'employes'])]
    private ?int $code_postal = null;

    #[ORM\Column(length: 255)]
    #[Serializer\Groups(['entreprise_ville', 'clients', 'commandes', 'employes'])]
    private ?string $ville = null;

    #[ORM\Column]
    #[Serializer\Groups(['entreprise_chiffre_affaire', 'clients', 'commandes', 'employes'])]
    private ?int $chiffre_affaire = null;


    #[ORM\OneToMany(mappedBy: 'Employes_entreprise', targetEntity: Employes::class)]
    #[Serializer\Groups(['entreprise_employes', 'clients', 'commandes', 'employes'])]
    private Collection $Employes_entreprise;


    #[ORM\OneToMany(mappedBy: "entreprise", targetEntity: Client::class)]
    #[Serializer\Groups(['entreprise_employes', 'clients', 'commandes', 'employes'])]
    private Collection $clients;


    public function __construct()
    {
        $this->Employes_entreprise = new ArrayCollection();
    }

    #[Serializer\Groups(['entreprise_id', 'clients', 'commandes', 'employes'])]
    public function getId(): ?int
    {
        return $this->id;
    }

    #[Serializer\Groups(['entreprise_nom', 'clients', 'commandes', 'employes'])]
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    #[Serializer\Groups(['entreprise_numero_siret', 'clients', 'commandes', 'employes'])]
    public function getNumeroSiret(): ?int
    {
        return $this->numero_siret;
    }

    public function setNumeroSiret(int $numero_siret): static
    {
        $this->numero_siret = $numero_siret;

        return $this;
    }

    #[Serializer\Groups(['entreprise_adresse', 'clients', 'commandes', 'employes'])]
    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    #[Serializer\Groups(['entreprise_code_postal', 'clients', 'commandes', 'employes'])]
    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    #[Serializer\Groups(['entreprise_ville', 'clients', 'commandes', 'employes'])]
    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    #[Serializer\Groups(['entreprise_chiffre_affaire', 'clients', 'commandes', 'employes'])]
    public function getChiffreAffaire(): ?int
    {
        return $this->chiffre_affaire;
    }

    public function setChiffreAffaire(int $chiffre_affaire): static
    {
        $this->chiffre_affaire = $chiffre_affaire;

        return $this;
    }

    public function getClients(): Collection
    {
        return $this->clients;
    }


    /**
     * @return Collection<int, Employes>
     */
    #[Serializer\Groups(['entreprise_employes', 'clients', 'commandes', 'employes'])]
    public function getEmployesEntreprise(): Collection
    {
        return $this->Employes_entreprise;
    }

    public function addEmployesEntreprise(Employes $employesEntreprise): static
    {
        if (!$this->Employes_entreprise->contains($employesEntreprise)) {
            $this->Employes_entreprise->add($employesEntreprise);
            $employesEntreprise->setEmployesEntreprise($this);
        }

        return $this;
    }

    public function removeEmployesEntreprise(Employes $employesEntreprise): static
    {
        if ($this->Employes_entreprise->removeElement($employesEntreprise)) {
            // set the owning side to null (unless already changed)
            if ($employesEntreprise->getEmployesEntreprise() === $this) {
                $employesEntreprise->setEmployesEntreprise(null);
            }
        }

        return $this;
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('numero_siret')
            ->add('adresse')
            ->add('code_postal')
            ->add('ville')
            ->add('chiffre_affaire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Employes;
use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use JMS\Serializer\SerializationContext;
use JMS\Serializer\SerializerBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/api', name: 'api_')]
class EntrepriseController extends AbstractController
{
    private $serializer;

    public function __construct()
    {
        $this->serializer = SerializerBuilder::create()->build();
    }

    #[Route('/all_clients_entreprise/{entrepriseId}', name: 'app_all_clients', methods: ['GET'])]
    public function getAllClientsByEntreprise(int $entrepriseId, EntrepriseRepository $entrepriseRepository): JsonResponse
    {
        $entreprise = $entrepriseRepository->findClientsByEntreprise($entrepriseId);

        if (!$entreprise) {
            return new JsonResponse(['error' => 'Entreprise non trouvée'], Response::HTTP_NOT_FOUND);
        }

        $clients = $entreprise->getClients(); // Supposons que vous avez une méthode "getClients" dans votre entité Entreprise

        $context = SerializationContext::create()->setGroups([
            'clients', // Ajoutez ici les groupes de sérialisation pour les clients
            'default',
        ]);

        $clientsJson = $this->serializer->serialize($clients, 'json', $context);

        return new JsonResponse(['clients' => json_decode($clientsJson)], Response::HTTP_OK, ['Content-Type' => 'application/json']);
    }

    #[Route('/count_clients_entreprise/{entrepriseId}', name: 'app_count_clients', methods: ['GET'])]
    public function countClientsByEntreprise(int $entrepriseId, EntrepriseRepository $entrepriseRepository): JsonResponse
    {
        $countsByStatus = $entrepriseRepository->countClientsByStatus($entrepriseId);

        return new JsonResponse(['countsByStatus' => $countsByStatus], Response::HTTP_OK, ['Content-Type' => 'application/json']);
    }


    #[Route('/all_entreprises', name: 'app_entreprise_index', methods: ['GET'])]
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        $entreprises = $entrepriseRepository->findAll();

        $context = SerializationContext::create()->setGroups([
            'entreprise_id',
            'entreprise_nom',
            'entreprise_numero_siret',
            'entreprise_adresse',
            'entreprise_code_postal',
            'entreprise_ville',
            'entreprise_chiffre_affaire',
            'entreprise_entreprise',
            'entreprise_employes_entreprise',
            'entreprise_entreprise_client',
            'default',
        ]);

        $entreprisesJson = $this->serializer->serialize($entreprises, 'json', $context);

        return new Response($entreprisesJson, Response::HTTP_OK, ['Content-Type' => 'application/json']);
    }

    #[Route('/count_entreprises', name: 'app_entreprises_count', methods: ['GET'])]
    public function count(EntrepriseRepository $entrepriseRepository): Response
    {
        $entreprise = $entrepriseRepository->findAll();

        $nombreTotalEntreprises = count($entreprise);

        $responseData = [
            'nombreTotalEntreprises' => $nombreTotalEntreprises,
        ];

        $responseJson = json_encode($responseData);

        return new Response($responseJson, Response::HTTP_OK, ['Content-Type' => 'application/json']);

    }

    #[Route('/new_entreprise', name: 'app_entreprise_new', methods: ['POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): JsonResponse
    {
        $decoded = json_decode($request->getContent());

        $entreprise = new Entreprise();
        $entreprise->setNom($decoded->nom);
        $entreprise->setNumeroSiret($decoded->numero_siret);
        $entreprise->setAdresse($decoded->adresse);
        $entreprise->setCodePostal($decoded->code_postal);
        $entreprise->setVille($decoded->ville);
        $entreprise->setChiffreAffaire($decoded->chiffre_affaire);

        $entityManager->persist($entreprise);
        $entityManager->flush();

        return $this->json([
            'success' => true,
            'message' => 'La nouvelle entreprise a été ajoutée avec succès.',
        ]);
    }

    #[Route('/{id}/show_entreprise', name: 'app_entreprise_show', methods: ['GET'])]
    public function show(Entreprise $entreprise): JsonResponse
    {
        $context = SerializationContext::create()->setGroups([
            'entreprise_id',
            'entreprise_nom',
            'entreprise_numero_siret',
            'entreprise_adresse',
            'entreprise_code_postal',
            'entreprise_ville',
            'entreprise_chiffre_affaire',
            'entreprise_entreprise',
            'entreprise_employes_entreprise',
            'entreprise_entreprise_client',
            'default',
        ]);

        $entrepriseJson = $this->serializer->serialize($entreprise, 'json', $context);

        return new JsonResponse(['entreprise' => json_decode($entrepriseJson)], JsonResponse::HTTP_OK, ['Content-Type' => 'application/json']);
    }

    #[Route('/{id}/edit_entreprise', name: 'app_entreprise_edit', methods: ['POST'])]
    public function edit(Request $request, Entreprise $entreprise, EntityManagerInterface $entityManager): JsonResponse
    {
        $decoded = json_decode($request->getContent());

        $entreprise->setNom($decoded->nom);
        $entreprise->setNumeroSiret($decoded->numero_siret);
        $entreprise->setAdresse($decoded->adresse);
        $entreprise->setCodePostal($decoded->code_postal);
        $entreprise->setVille($decoded->ville);
        $entreprise->setChiffreAffaire($decoded->chiffre_affaire);

        $entityManager->flush();

        return $this->json([
            'success' => true,
            'message' => 'Les informations de l\'entreprise ont été mises à jour avec succès.',
        ]);
    }

    #[Route('/{id}/delete_entreprise', name: 'app_entreprise_delete', methods: ['POST'])]
    public function delete(Request $request, Entreprise $entreprise, EntityManagerInterface $entityManager): JsonResponse
    {
        $employe = $entityManager->getRepository(Employes::class)->findOneBy(['Employes_entreprise' => $entreprise]);
        if ($employe) {
            $entityManager->remove($employe);
        }
        $entityManager->remove($entreprise);
        $entityManager->flush();

        return $this->json([
            'success' => true,
            'message' => 'L\'entreprise a été supprimée avec succès.',
        ]);
    }
}

templates/entreprise/_delete_form.html.twig
<form method="post" action="{{ path('app_entreprise_delete', {'id': entreprise.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entreprise.id) }}">
    <button class="btn">Delete</button>
</form>

templates/entreprise/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Entreprise{% endblock %}

{% block body %}
    <h1>Edit Entreprise</h1>

    {{ include('entreprise/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_entreprise_index') }}">back to list</a>

    {{ include('entreprise/_delete_form.html.twig') }}
{% endblock %}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise index{% endblock %}

{% block body %}
    <h1>Entreprise index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Numero_siret</th>
                <th>Adresse</th>
                <th>Code_postal</th>
                <th>Ville</th>
                <th>Chiffre_affaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entreprise in entreprises %}
            <tr>
                <td>{{ entreprise.id }}</td>
                <td>{{ entreprise.nom }}</td>
                <td>{{ entreprise.numeroSiret }}</td>
                <td>{{ entreprise.adresse }}</td>
                <td>{{ entreprise.codePostal }}</td>
                <td>{{ entreprise.ville }}</td>
                <td>{{ entreprise.chiffreAffaire }}</td>
                <td>
                    <a href="{{ path('app_entreprise_show', {'id': entreprise.id}) }}">show</a>
                    <a href="{{ path('app_entreprise_edit', {'id': entreprise.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_entreprise_new') }}">Create new</a>
{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Entreprise{% endblock %}

{% block body %}
    <h1>Create new Entreprise</h1>

    {{ include('entreprise/_form.html.twig') }}

    <a href="{{ path('app_entreprise_index') }}">back to list</a>
{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise{% endblock %}

{% block body %}
    <h1>Entreprise</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entreprise.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ entreprise.nom }}</td>
            </tr>
            <tr>
                <th>Numero_siret</th>
                <td>{{ entreprise.numeroSiret }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ entreprise.adresse }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ entreprise.codePostal }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ entreprise.ville }}</td>
            </tr>
            <tr>
                <th>Chiffre_affaire</th>
                <td>{{ entreprise.chiffreAffaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_entreprise_index') }}">back to list</a>

    <a href="{{ path('app_entreprise_edit', {'id': entreprise.id}) }}">edit</a>

    {{ include('entreprise/_delete_form.html.twig') }}
{% endblock %}